version: "3.7"

services:
  payments_gateway_svc:
    entrypoint: ""
    image: payments_gateway_local
    container_name: payments_gateway
    environment:
      ASPNETCORE_URLS: "http://*:8080"
      ASPNETCORE_ENVIRONMENT: "DockerEnv"
    links:
      - bank_of_uk_simulator
    ports:
      - "63120:8080"

  bank_of_uk_simulator:
    entrypoint: ""
    image: bank_of_uk_local
    container_name: bank_of_uk
    environment:
      ASPNETCORE_URLS: "http://*:8080"
      ASPNETCORE_ENVIRONMENT: "DockerEnv"
    ports:
      - "63123:8080"
    expose:
      - "63123"